export const products = [
  {
    id: 1,
    name: 'Basic Tee',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    category: 'Tee',
    color: 'Black',
  },
  {
    id: 2,
    name: 'Classic White Shirt',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-02.jpg',
    imageAlt: "Front of men's Classic White Shirt.",
    price: '$45',
    category: 'Shirt',
    color: 'White',
  },
  {
    id: 3,
    name: 'Casual Blue Jeans',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-03.jpg',
    imageAlt: "Front of men's Casual Blue Jeans.",
    price: '$55',
    category: 'Jeans',
    color: 'gray',
  },
  {
    id: 4,
    name: 'Comfortable Hoodie',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-04.jpg',
    imageAlt: "Front of men's Comfortable Hoodie.",
    price: '$60',
    category: 'Hoodie',
    color: 'orange',
  },
  {
    id: 5,
    name: 'Sporty Joggers',
    imageSrc: 'https://img.freepik.com/free-photo/blue-t-shirt_125540-727.jpg',
    imageAlt: "Front of men's Sporty Joggers.",
    price: '$50',
    category: 'Joggers',
    color: 'green',
  },
  {
    id: 6,
    name: 'Stylish Jacket',
    imageSrc: 'https://cdn.salla.sa/bRXPEW/b70d042c-eb6f-4e56-ba77-f9cd535d1f3f-397.65319426336x500-mlrSO6qLqefx1ysgJDvWAchN2qd0ZgF2e5KVUT5D.png',
    imageAlt: "Front of men's Stylish Jacket.",
    price: '$80',
    category: 'Jacket',
    color: 'Brown',
  },
  {
    id: 7,
    name: 'Summer Shorts',
    imageSrc: 'https://static.vecteezy.com/system/resources/thumbnails/041/329/735/small_2x/ai-generated-blank-red-t-shirt-with-hanger-isolated-on-transparent-background-short-sleeve-t-shirt-generative-ai-png.png',
    imageAlt: "Front of men's Summer Shorts.",
    price: '$30',
    category: 'Shorts',
    color: 'red',
  },
  {
    id: 8,
    name: 'Elegant Blazer',
    imageSrc: 'https://media.zid.store/cdn-cgi/image/w=235,q=100,f=auto/https://media.zid.store/0ae3f82c-3658-4c12-9024-338d45195dc6/1b132bb8-4a66-4f8d-8ebd-ae732481ccb2-260x260.png',
    imageAlt: "Front of men's Elegant Blazer.",
    price: '$100',
    category: 'Blazer',
    color: 'Navy Blue',
  },
];
