export const Products = [
  {
    id: 1,
    name: 'Basic Tee',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    category: 'Tee',
    color: 'Black',
  },
  {
    id: 2,
    name: 'Classic White Shirt',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-02.jpg',
    imageAlt: "Front of men's Classic White Shirt.",
    price: '$45',
    category: 'Shirt',
    color: 'White',
  },
  {
    id: 3,
    name: 'Casual Blue Jeans',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-03.jpg',
    imageAlt: "Front of men's Casual Blue Jeans.",
    price: '$55',
    category: 'Jeans',
    color: 'gray',
  },
  {
    id: 4,
    name: 'Comfortable Hoodie',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-04.jpg',
    imageAlt: "Front of men's Comfortable Hoodie.",
    price: '$60',
    category: 'Hoodie',
    color: 'orange',
  },
  {
    id: 5,
    name: 'Sporty Joggers',
    imageSrc: 'https://img.freepik.com/free-photo/blue-t-shirt_125540-727.jpg',
    imageAlt: "Front of men's Sporty Joggers.",
    price: '$50',
    category: 'Joggers',
    color: 'green',
  },
  {
    id: 6,
    name: 'Stylish Jacket',
    imageSrc: 'https://cdn.salla.sa/bRXPEW/b70d042c-eb6f-4e56-ba77-f9cd535d1f3f-397.65319426336x500-mlrSO6qLqefx1ysgJDvWAchN2qd0ZgF2e5KVUT5D.png',
    imageAlt: "Front of men's Stylish Jacket.",
    price: '$80',
    category: 'Jacket',
    color: 'Brown',
  },
  {
    id: 7,
    name: 'Summer Shorts',
    imageSrc: 'https://static.vecteezy.com/system/resources/thumbnails/041/329/735/small_2x/ai-generated-blank-red-t-shirt-with-hanger-isolated-on-transparent-background-short-sleeve-t-shirt-generative-ai-png.png',
    imageAlt: "Front of men's Summer Shorts.",
    price: '$30',
    category: 'Shorts',
    color: 'red',
  },
  {
    id: 8,
    name: 'Elegant Blazer',
    imageSrc: 'https://media.zid.store/cdn-cgi/image/w=235,q=100,f=auto/https://media.zid.store/0ae3f82c-3658-4c12-9024-338d45195dc6/1b132bb8-4a66-4f8d-8ebd-ae732481ccb2-260x260.png',
    imageAlt: "Front of men's Elegant Blazer.",
    price: '$100',
    category: 'Blazer',
    color: 'Navy Blue',
  },
  
  {
    id: 9,
    name: 'Dress',
    imageSrc: 'https://purepng.com/public/uploads/large/purepng.com-girl-dressuncategorizedgirl-dressfashion-girl-women-dress-cloth-apparel-631522326781b64q4.png',
    imageAlt: "Front of women's Vintage Dress.",
    price: '$65',
    category: 'Dress',
    color: 'Blue',
  },
  {
    id: 10,
    name: 'chemise',
    imageSrc: 'https://freepngimg.com/thumb/dress_shirt/4-black-dress-shirt-png-image-thumb.png',
    imageAlt: "Front of men's Denim Jacket.",
    price: '$85',
    category: 'chemise',
    color: 'Black',
  },
  {
    id: 11,
    name: 'Red Dress',
    imageSrc: 'https://pngimg.com/d/dress_PNG53.png',
    imageAlt: "Front of women's Slim Fit Dress.",
    price: '$40',
    category: 'Robe',
    color: 'Red',
  },
  {
    id: 12,
    name: 'Cozy chemise',
    imageSrc: 'https://img.freepik.com/free-psd/two-shirts-are-checkered-surface-isolated-transparent-background_191095-22114.jpg',
    imageAlt: "Front of men's Cozy chemise.",
    price: '$55',
    category: 'chemise',
    color: 'Beige',
  },
  {
    id: 13,
    name: 'Black Cap',
    imageSrc: 'https://static.vecteezy.com/system/resources/thumbnails/008/532/936/small/black-cap-mockup-cutout-file-png.png',
    imageAlt: "Front of men's Cap.",
    price: '$35',
    category: 'Cap',
    color: 'Black',
  },
  {
    id: 14,
    name: 'Black Shoes',
    imageSrc: 'https://i.pinimg.com/564x/4f/c4/1c/4fc41cd322fb689a75d54d86098a1663.jpg',
    imageAlt: "Front of men's Shoes.",
    price: '$50',
    category: 'Shoes',
    color: 'White and Black',
  },
  {
    id: 15,
    name: 'Graphic Tee',
    imageSrc: 'https://static.vecteezy.com/system/resources/thumbnails/021/938/733/small_2x/blue-jeans-isolated-on-a-transparent-background-png.png',
    imageAlt: "Front of men's Jeans.",
    price: '$25',
    category: 'Jeans',
    color: 'Blue',
  },
  {
    id: 16,
    name: 'Leather Belt',
    imageSrc: 'https://img.freepik.com/free-photo/t-shirt_1203-8005.jpg',
    imageAlt: "Men's T-shirts.",
    price: '$45',
    category: 'shirt',
    color: 'Brown',
  },
];
